// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fizzBuzz.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FizzBuzzRequest struct {
	Int1                 int32    `protobuf:"varint,1,opt,name=int1,proto3" json:"int1,omitempty"`
	Int2                 int32    `protobuf:"varint,2,opt,name=int2,proto3" json:"int2,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Str1                 string   `protobuf:"bytes,4,opt,name=str1,proto3" json:"str1,omitempty"`
	Str2                 string   `protobuf:"bytes,5,opt,name=str2,proto3" json:"str2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FizzBuzzRequest) Reset()         { *m = FizzBuzzRequest{} }
func (m *FizzBuzzRequest) String() string { return proto.CompactTextString(m) }
func (*FizzBuzzRequest) ProtoMessage()    {}
func (*FizzBuzzRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fizzBuzz_44e9bb35559097be, []int{0}
}
func (m *FizzBuzzRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FizzBuzzRequest.Unmarshal(m, b)
}
func (m *FizzBuzzRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FizzBuzzRequest.Marshal(b, m, deterministic)
}
func (dst *FizzBuzzRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FizzBuzzRequest.Merge(dst, src)
}
func (m *FizzBuzzRequest) XXX_Size() int {
	return xxx_messageInfo_FizzBuzzRequest.Size(m)
}
func (m *FizzBuzzRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FizzBuzzRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FizzBuzzRequest proto.InternalMessageInfo

func (m *FizzBuzzRequest) GetInt1() int32 {
	if m != nil {
		return m.Int1
	}
	return 0
}

func (m *FizzBuzzRequest) GetInt2() int32 {
	if m != nil {
		return m.Int2
	}
	return 0
}

func (m *FizzBuzzRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FizzBuzzRequest) GetStr1() string {
	if m != nil {
		return m.Str1
	}
	return ""
}

func (m *FizzBuzzRequest) GetStr2() string {
	if m != nil {
		return m.Str2
	}
	return ""
}

type FizzBuzzResponse struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FizzBuzzResponse) Reset()         { *m = FizzBuzzResponse{} }
func (m *FizzBuzzResponse) String() string { return proto.CompactTextString(m) }
func (*FizzBuzzResponse) ProtoMessage()    {}
func (*FizzBuzzResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fizzBuzz_44e9bb35559097be, []int{1}
}
func (m *FizzBuzzResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FizzBuzzResponse.Unmarshal(m, b)
}
func (m *FizzBuzzResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FizzBuzzResponse.Marshal(b, m, deterministic)
}
func (dst *FizzBuzzResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FizzBuzzResponse.Merge(dst, src)
}
func (m *FizzBuzzResponse) XXX_Size() int {
	return xxx_messageInfo_FizzBuzzResponse.Size(m)
}
func (m *FizzBuzzResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FizzBuzzResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FizzBuzzResponse proto.InternalMessageInfo

func (m *FizzBuzzResponse) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*FizzBuzzRequest)(nil), "fizz_buzz.FizzBuzzRequest")
	proto.RegisterType((*FizzBuzzResponse)(nil), "fizz_buzz.FizzBuzzResponse")
}

func init() { proto.RegisterFile("fizzBuzz.proto", fileDescriptor_fizzBuzz_44e9bb35559097be) }

var fileDescriptor_fizzBuzz_44e9bb35559097be = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xcb, 0xac, 0xaa,
	0x72, 0x2a, 0xad, 0xaa, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xf1, 0xe3, 0x93,
	0x4a, 0xab, 0xaa, 0x94, 0xca, 0xb9, 0xf8, 0xdd, 0xa0, 0x92, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5,
	0x25, 0x42, 0x42, 0x5c, 0x2c, 0x99, 0x79, 0x25, 0x86, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41,
	0x60, 0x36, 0x54, 0xcc, 0x48, 0x82, 0x09, 0x2e, 0x66, 0x24, 0x24, 0xc2, 0xc5, 0x9a, 0x93, 0x99,
	0x9b, 0x59, 0x22, 0xc1, 0x0c, 0x16, 0x84, 0x70, 0x40, 0x2a, 0x8b, 0x4b, 0x8a, 0x0c, 0x25, 0x58,
	0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0xa8, 0x98, 0x91, 0x04, 0x2b, 0x5c, 0xcc, 0x48, 0x49,
	0x8b, 0x4b, 0x00, 0x61, 0x71, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x18, 0x17, 0x5b, 0x59,
	0x62, 0x4e, 0x69, 0x6a, 0xb1, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0x67, 0x10, 0x94, 0xe7, 0xc4, 0x1d,
	0x85, 0x70, 0x71, 0x12, 0x1b, 0xd8, 0x0f, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0x80,
	0xcf, 0x7f, 0xd5, 0x00, 0x00, 0x00,
}
